version: '3.8'

services:
  app:
    build: .
    image: achu2002/url-shortner:latest 
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
