const SECREATS = {
  FIREBASE_APIKEY: process.env.FIREBASE_APIKEY,
  FIREBASE_AUTHDOMAIN: process.env.FIREBASE_AUTHDOMAIN,
  FIREBASE_PROJECTID: process.env.FIREBASE_PROJECTID,
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGINGSENDERID: process.env.FIREBASE_MESSAGINGSENDERID,
  FIREBASE_APPID: process.env.FIREBASE_APPID,
};

export default SECREATS;
